CREATE OR REPLACE PROCEDURE MM_ADD_AUTH (
  GROUP_NAME IN VARCHAR2,
  AUTH_NAME IN VARCHAR2,
  LOCALE_NAME IN NVARCHAR2
)
IS
NEXT_ID NUMBER;
AUTH_GROUP_ID NUMBER;
EXIST_COUNT NUMBER;
BEGIN
  SELECT MAX(ID)+1 INTO NEXT_ID FROM mm_authority;
  IF (NEXT_ID IS NULL) THEN
    NEXT_ID:=1;
  END IF;
  SELECT COUNT(ID) INTO EXIST_COUNT FROM mm_authority WHERE NAME=AUTH_NAME;
  IF (EXIST_COUNT > 0) THEN
  	dbms_output.put_line('Same authority exists.');
    RETURN;
  END IF;
  
  SELECT ID INTO AUTH_GROUP_ID FROM mm_auth_group WHERE NAME= group_name;
  IF (AUTH_GROUP_ID IS NOT NULL) THEN
    INSERT INTO mm_authority (id, type, name, locale_zh_cn)
      VALUES (NEXT_ID, AUTH_GROUP_ID, AUTH_NAME, LOCALE_NAME);
  ELSE
  	dbms_output.put_line('Auth group is not found.');
    RAISE NO_DATA_FOUND;
  END IF;
EXCEPTION
WHEN NO_DATA_FOUND THEN
 ROLLBACK;
END;